pull_request_rules:
  - name: Assign reviewer
    conditions:
      - "#approved-reviews-by>=0"
    actions:
      review:
        approve:
          reviewers:
            - "sudhanshuvlog"
        message: "Requesting review from Sudhanshu"

  - name: Merge on approval and successful workflow
    conditions:
      - "#approved-reviews-by>=1"
      - "check-success=main.yml"
    actions:
      merge:
        method: merge
      comment:
        message: "Merged successfully after approval and successful workflow (mergebot.yml)"
