pull_request_rules:
  - name: Assign reviewer
    conditions:
      - "#created"
    actions:
      assign:
        add_users:
          - "sudhanshuvlog"
      comment:
        message: "Sudhanshu is been added as the reviewer"

  - name: Merge on approval and successful workflow
    conditions:
      - "#approved-reviews-by>=1"
      - "check-success=main.yml"
    actions:
      merge:
        method: merge
      comment:
        message: "Merged successfully after approval and successful workflow (mergebot.yml)"
