pull_request_rules:
  - name: Assign reviewer
    conditions:
      - "#files>=1"
    actions:
      request_reviews:
        users:
            - "sudhanshuvlog"
      comment:
        message: "Requesting review from Sudhanshu"
        
      # github_actions:
      #   workflow:
      #     dispatch:
      #       - workflow: python-package.yml
            
  - name: Merge on approval and successful workflow
    conditions:
      - "#approved-reviews-by>=1"
      - "check-success=python-package.yml"
    actions:
      merge:
        method: merge
      comment:
        message: "Merged successfully after approval and successful workflow (mergebot.yml)"
