pull_request_rules:
  - name: Automatic merge
    actions:
        assign:
            add_users:
                - "sudhanshuvlog"
        comment:
            message: "Sudhanshu is been added as the reviewer"

pull_request_rules:
  - name: Automatic merge
    conditions:
      - "#approved-reviews-by>=1"
      - check-success = mergebot.yml
    actions:
        merge:
            method: merge
        comment: 
            message: "merged yeeeee"
      